name: vipwpdevenv
recipe: wordpress
env_file:
  - .env
config:
  webroot: wp
  php: '7.3'
  via: nginx
  database: mariadb
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/tutorials/php.html#toggling-xdebug
  xdebug: true
  config:
    vhosts: configs/nginx-wordpress.conf
    php: configs/php.ini
proxy:
  appserver_nginx:
    - vip-go-dev.lndo.site
services:
  appserver:
    overrides:
      volumes:
        - ./mu-plugins:/app/wp/wp-content/mu-plugins
        - ./wp/wp-content/plugins:/app/wp/wp-content/plugins
        - ./wp/wp-content/themes:/app/wp/wp-content/themes
    run:
      - bash /app/bin/lando/setup.sh
    build_as_root:
      - apt-get update -y && apt-get install -y subversion openjdk-8-jdk
    composer:
      phpunit/phpunit: '^6'
  vip-search:
    type: elasticsearch:7
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
tooling:
  test:
    service: appserver
    description: "Run all tests: lando test"
    cmd:
      - cd /app/wp/wp-content/mu-plugins && phpunit
  add-fake-data:
    service: appserver
    description: "Add fake data of 5 images, 50 users, 1000 posts. Files for generation in 'configs/faker', edit them or use faker directly for other needs. Append --debug to see more details."
    cmd:
     - wp faker fake /app/configs/faker/test_images.yml /app/configs/faker/test_users.yml /app/configs/faker/test_posts.yml
  delete-fake-data:
    service: appserver
    description: "Delete all fake data generated by faker"
    cmd:
     - wp faker delete
  jmeter:
    service: appserver
    description: "JMeter interface"
    cmd:
      - cd /app/jmeter-test-files && /bin/sh /usr/local/bin/apache-jmeter-5.2.1/bin/jmeter -n
