Trendwerk\Faker\Entity\User:
  user{1..50}:
    user_login: '<username()>'
    user_pass: '<username()>'
    first_name: '<firstName()>'
    last_name: '<lastName()>'
    display_name: '<firstName()> <lastName()>'
    user_email: '<email()>'
    role: 'author'
